#!/usr/bin/env bash
#
# Install the systemd units that are not generated by another installer.
#
# The housekeeping/disk-guard and bed-state units are written by
# install_motion_housekeeping_timer.sh and install_bed_state_timer.sh
# respectively; this script covers the rest:
#
#   motion.service.d/override.conf  Motion config path + pipeline env vars
#   motion-score-worker.service     Queue-based snapshot scoring worker
#   motion-selftest.service         On-demand end-to-end check
#   motion-debug-viewer.service     Optional LAN gallery of scored frames
#   fart-api.service                JSON API behind the dashboard
#   pipewire-motion-acl.service     Lets the motion user reach PipeWire audio
#
# Usage:
#   cd ~/pi-motion-vision
#   ./scripts/install_systemd_units.sh
#
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_DIR="$REPO_DIR/etc/systemd"
DEST_DIR="/etc/systemd/system"

# Units that stay disabled unless you ask for them. The debug viewer serves
# scored frames over the LAN with no authentication, and the fart API binds
# 0.0.0.0, so neither should start automatically.
OPTIONAL_UNITS="motion-debug-viewer.service fart-api.service"

echo "Installing systemd units from: $SRC_DIR"

install_unit() {
  local src="$1"
  local dest="$2"

  if [ ! -f "$src" ]; then
    echo "  Skip (missing source): $src"
    return 0
  fi

  if [ -f "$dest" ] && ! cmp -s "$src" "$dest"; then
    echo "  Backing up: $dest"
    sudo cp -a "$dest" "$dest.bak.$(date +%Y%m%d%H%M%S)"
  fi

  sudo install -m 0644 -o root -g root "$src" "$dest"
  echo "  Installed: $dest"
}

# The drop-in carries the repo path, so rewrite it for wherever this clone lives.
echo
echo "Motion drop-in override"
sudo mkdir -p "$DEST_DIR/motion.service.d"
OVERRIDE_TMP="$(mktemp)"
trap 'rm -f "$OVERRIDE_TMP"' EXIT
sed "s|^Environment=PI_MOTION_VISION_REPO=.*|Environment=PI_MOTION_VISION_REPO=$REPO_DIR|" \
  "$SRC_DIR/motion.service.d/override.conf" > "$OVERRIDE_TMP"
install_unit "$OVERRIDE_TMP" "$DEST_DIR/motion.service.d/override.conf"

echo
echo "Service units"
for src in "$SRC_DIR"/*.service; do
  [ -e "$src" ] || continue
  install_unit "$src" "$DEST_DIR/$(basename "$src")"
done

echo
sudo systemctl daemon-reload

echo "Enabling units"
sudo systemctl enable --now motion-score-worker.service pipewire-motion-acl.service
sudo systemctl enable motion-selftest.service
sudo systemctl restart motion.service

echo
echo "Installed. Optional units were left disabled:"
for unit in $OPTIONAL_UNITS; do
  echo "  sudo systemctl enable --now $unit"
done

echo
echo "Verify with:"
echo "  systemctl status motion.service motion-score-worker.service"
echo "  sudo /usr/local/bin/motion_self_test.sh"
